#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/chef',
   :ref => 'master'